version: "3.3"

services:

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    networks:
      - transcendence

  backend:
    image: node:18-alpine
    restart: always
    command: sh -c 'npm install; npm run start:dev'
    working_dir: /backend
    environment:
      CLIENT_ID: "${CLIENT_ID}"
      CLIENT_SECRET: "${CLIENT_SECRET}"
      INTRA_CLIENT_ID: "${INTRA_CLIENT_ID}"
      INTRA_CLIENT_SECRET: "${INTRA_CLIENT_SECRET}"
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_USER}?schema=public"
    volumes:
      - ./backend:/backend
      - ./avatar:/backend/avatar
    depends_on:
      - db
    ports:
      - 3001:3000
      - 5555:5555
    networks:
      - transcendence

  frontend:
    image: node:18-alpine
    restart: always
    command: sh -c 'npm install; npm run dev'
    # command:  sh -c 'sleep 1000000000'
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
      - ./avatar:/frontend/public/avatar
    depends_on:
      - db
    ports:
      - 3000:3000
      - 24678:24678 # For HMR
    environment:
      HOST: 0.0.0.0
      BACKEND_URL: http://localhost:3001/api/v0
    
    networks:
      - transcendence

volumes:
  db-data:
    driver: local

networks:
  transcendence:
    driver: bridge